[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.1"  # Specific LTS version

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enableStaticFileOptimization = true
    enableImageOptimization = true

[dev]
  framework = "next"
  targetPort = 3000
  publish = ".next"
