[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "22.0.0"  # Updated to Node.js 22

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
  targetPort = 3000
  publish = ".next"
